eregister/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard:start')),
    path('dashboard/', include('records.urls.dashboard')),
    path('lesson/', include('records.urls.lesson')),
    path('student/', include('records.urls.student')),
    path('group/', include('records.urls.group')),
    path('auth/', include('records.urls.auth')),
    path('schedule/', include('records.urls.schedule')),
    path('ajax/', include('records.urls.ajax')),
    path('admin/', admin.site.urls),
]

records/models/course.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Course(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=50,
        blank=False,
        null=False,
        help_text=_('Required')
    )

    group = models.ForeignKey(
        'records.StudentGroup',
        verbose_name=_('Student group'),
        blank=False,
        null=False,
        on_delete=models.PROTECT,
        related_name='courses'
    )

    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')
        ordering = ['name']
        unique_together = ['name', 'group']

    def __str__(self):
        # return "%(name)s (%(group)s)" % {
        #     'name': self.name,
        #     'group': self.group.name
        # }
        return str(self.name)

records/models/lesson.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from records.models import attendance
import datetime


class Lesson(models.Model):
    STATUS_PLANNED = 0
    STATUS_REALIZED = 1
    STATUS_CANCELLED = 2
    STATUS_CHOICES = [
        (STATUS_PLANNED, _('Unrealized')),
        (STATUS_REALIZED, _('Realized')),
        (STATUS_CANCELLED, _('Cancelled')),
    ]

    status = models.IntegerField(
        _('Status'),
        blank=False,
        null=False,
        choices=STATUS_CHOICES,
        default=STATUS_PLANNED
    )

    schedule = models.ForeignKey(
        'records.Schedule',
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        verbose_name=_('Schedule entry'),
        related_name='lessons'
    )

    date = models.DateField(
        _('Date'),
        blank=False,
        null=False
    )

    subject = models.CharField(
        _('Subject'),
        blank=True,
        max_length=255,
    )

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')
        ordering = ['-date']
        unique_together = ['schedule', 'date']

    @property
    def is_realized(self):
        return self.status == self.STATUS_REALIZED

    @property
    def is_cancelled(self):
        return self.status == self.STATUS_CANCELLED

    @property
    def is_editable(self):
        return self.date <= datetime.date.today()

    @property
    def short_subject(self):
        subject = self.subject
        return subject if len(subject) < 100 else (subject[:95] + "(...)")

    @classmethod
    def from_dates(cls, schedule, dates):
        """ Bulk create Lessons from dates list"""
        objs = [Lesson(schedule=schedule, date=date) for date in dates]
        Lesson.objects.bulk_create(objs)

    def sync_attendances(self):
        """
        Create Attendances related to Lesson. If lesson is cancelled,
        delete all related attendances
        """

        # delete attendances for cancelled lesson and exit
        if self.is_cancelled:
            self.attendances.all().delete()
            return

        # get list of students by date
        group = self.schedule.course.group
        students = group.get_students_by_date(self.date)

        # create list of students that don't have related Attendance created
        missing_attendances = list(students)
        for att in self.attendances.all():
            if att.student in missing_attendances:
                missing_attendances.remove(att.student)
            else:
                att.delete()

        # create missing Attendances
        for student in missing_attendances:
            attendance.Attendance(lesson=self, student=student).save()

    def get_absolute_url(self):
        return reverse("lesson:update", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.date)

records/models/schedule.py
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from records.models import lesson


class Schedule(models.Model):

    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6
    DAYS_OF_WEEK = [
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Thursday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
        (SUNDAY, _('Sunday')),
    ]

    course = models.ForeignKey(
        'records.Course',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Course')
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_teacher': True},
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Teacher')
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    day_of_week = models.IntegerField(
        _('Day of the week'),
        blank=True,
        choices=DAYS_OF_WEEK
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    period = models.ForeignKey(
        'records.Period',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Period')
    )

    class Meta:
        verbose_name = _('Schedule entry')
        verbose_name_plural = _('Schedule entries')
        ordering = ['date_start']

    def save(self, *args, **kwargs):
        """ Override save method to make it atomic with post_save signal """
        with transaction.atomic():
            super().save(*args, **kwargs)

    def _get_same_time_entries_qs(self):
        """
        Return queryset for schedule entries with same period and weekday,
        and overlaping dates
        """
        qs = Schedule.objects.filter(
            date_start__lte=self.date_end,
            date_end__gte=self.date_start,
            day_of_week=self.day_of_week,
            period=self.period
        ).select_related('teacher', 'course', 'period')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def _get_collisions_by_group(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(course__group=self.course.group)
        return list(qs)

    def _get_collisions_by_teacher(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(teacher=self.teacher)
        return list(qs)

    def _check_collisions(self):
        """
        Check for collisions (if selected teacher or student group
        already have planned lesson at that time)
        """
        raise_error = False
        errors = {}
        qs = self._get_same_time_entries_qs()
        collisions_group = self._get_collisions_by_group(qs)
        collisions_teacher = self._get_collisions_by_teacher(qs)
        error_msg = _("Colliding entries: %(collisions)s")
        if collisions_group:
            errors['course'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_group))
            }
            raise_error = True
        if collisions_teacher:
            errors['teacher'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_teacher))
            }
            raise_error = True

        if raise_error:
            raise ValidationError(errors)

    def clean(self) -> None:
        super().clean()
        # check if ending date isn't earlier than starting date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _("Ending date can't "
                              "be earlier than starting date.")
            })

        # limit schedule length
        dates_diff = self.date_end - self.date_start
        if dates_diff.days > 365:
            raise ValidationError({
                'date_end': _("Schedule length can't exceed 365 days.")
            })

        self.day_of_week = self.date_start.weekday()
        self._check_collisions()

    @property
    def is_editable(self):
        """
        Check for related Lessons with realized or cancelled status.
        Return False if any exist, True otherwise. Used in Schedule
        update view to limit modifiable fields.
        """
        qs = self.lessons.exclude(status=lesson.Lesson.STATUS_PLANNED)
        return False if qs.exists() else True

    def __str__(self) -> str:
        return "{}, {}, {} ({}, {} - {})".format(
            self.course,
            self.course.group,
            self.teacher,
            self.period,
            self.date_start,
            self.date_end
        )

    def get_absolute_url(self):
        kwargs = {
            'pk': self.course.group.pk,
            'date': self.date_start,
            'full_week': 1,
        }
        return reverse_lazy("group:schedule-specified", kwargs=kwargs)

records/models/studentgroup.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()


class StudentGroup(models.Model):
    """
    Group of Users without teacher status.
    - StudentGroup_obj.educator - User object set as educator
    """
    class Meta:
        verbose_name = _('Student group')
        verbose_name_plural = _('Student groups')
        ordering = ['name', ]

    name = models.CharField(
        _('Name'),
        blank=False,
        unique=True,
        max_length=30,
    )

    # Educator responsible for the group.
    # Limit choices to Users with is_teacher set to True
    educator = models.OneToOneField(
        verbose_name=_('Educator'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': True},
        related_name='educated_group'
    )

    def get_assignments_by_date(self, date=None):
        """
        Return queryset of assignments to the group for specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        qs = self.assignments.filter(
            date_start__lte=date,
            date_end__gte=date,
        ).select_related('student')
        return qs

    def get_all_assignments(self):
        """
        Return queryset for all assignemts to the group,
        including out of date assignments
        """
        qs = self.assignments.select_related('student')
        return qs

    def get_students_by_date(self, date=None):
        """
        Return queryset of students assigned to the group on specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        assignments = self.get_assignments_by_date(date)
        current_students = User.objects.filter(
            assignments__in=assignments)
        return current_students

    def get_all_students(self):
        """
        Return queryset of all students assigned to the group,
        including out of date assignments
        """
        all_students = User.objects.filter(
            assignments__in=self.assignments.all()
        ).distinct()
        return all_students

    @property
    def current_assignments(self): return self.get_assignments_by_date()

    @property
    def current_students(self): return self.get_students_by_date()

    def get_absolute_url(self):
        return reverse_lazy('group:detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return str(self.name)


class StudentGroupAssignment(models.Model):
    class Meta:
        verbose_name = _('Group assignment')
        verbose_name_plural = _('Group assignments')
        ordering = ['student__last_name', 'student__first_name', 'date_start']

    student = models.ForeignKey(
        verbose_name=_('Student'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': False},
        related_name='assignments'
    )

    group = models.ForeignKey(
        verbose_name=_('Student group'),
        to=StudentGroup,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        related_name='assignments'
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    def _get_colliding_assignments(self):
        qs = StudentGroupAssignment.objects.filter(
            student=self.student,
            date_start__lte=self.date_end,
            date_end__gte=self.date_start
        ).select_related('student', 'group')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def clean(self):
        super().clean()

        # check if ending date is not earlier than start date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _(
                    "End date can't be earlier than start date."
                )
            })
        colliding_assignments = list(self._get_colliding_assignments())
        if colliding_assignments:
            raise ValidationError(
                _("Colliding assigments for %(student)s: %(collisions)s"),
                params={
                    'student': str(self.student),
                    'collisions': ", ".join(map(str, colliding_assignments)),
                }
            )

    def __str__(self):
        return "{} ({} - {})".format(
            self.group, self.date_start, self.date_end
        )

records/forms/group.py
from records.models.course import Course
from django import forms
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from records.utils.user import get_students_without_group
from records.models import StudentGroup
from datetime import date

User = get_user_model()


class GroupCreateForm(forms.ModelForm):
    """
    'educator' field is limited to teachers without StudentGroup assigned.
    """
    educator = forms.ModelChoiceField(
        queryset=User.objects.filter(
            educated_group=None, is_teacher=True),
        required=True
    )

    class Meta:
        model = StudentGroup
        fields = ['name', 'educator']


class GroupUpdateForm(forms.ModelForm):
    """
    'educator' field is limited to teachers without StudentGroup assigned
    and current group's educator.
    """
    educator = forms.ModelChoiceField(
        queryset=None,
        required=True
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['educator'].queryset = User.objects.filter(
            Q(educated_group=None, is_teacher=True)
            | Q(pk=self.instance.educator.pk)
        )
        self.fields['educator'].initial = self.instance.educator

    class Meta:
        model = StudentGroup
        fields = ['name', 'educator']


class AssignManyToGroupForm(forms.Form):
    """
    Assign multiple students to group.
    Limit select choices to students without actual assignment.
    """
    students_to_add = forms.ModelMultipleChoiceField(
        queryset=get_students_without_group(),
        label=_('Students'),
        help_text=_(
            "Only students currently not assigned to any group are shown. "
            "Students with up-to-date assignment, "
            "can be edited from their profile."
        ),
        required=True,
    )

    date_start = forms.DateField(
        label=_('Start date'),
        required=True,
    )

    date_end = forms.DateField(
        label=_('End date'),
        required=True,
    )

    def clean(self):
        cleaned_data = super().clean()

        d_start = cleaned_data.get('date_start')
        d_end = cleaned_data.get('date_end')
        if d_end < d_start:
            raise ValidationError({
                'date_end': _(
                    "End date can't be earlier than start date."
                )
            })


class CourseCreateForm(forms.ModelForm):
    group = forms.ModelChoiceField(
        queryset=StudentGroup.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    class Meta:
        model = Course
        fields = '__all__'


class GroupDateScheduleForm(forms.Form):
    """ Used for filtering group's schedule on group's info page """
    date = forms.DateField(
        initial=date.today,
        required=True
    )

    full_week = forms.BooleanField(
        initial=True,
        label=_('Show whole week'),
        required=False
    )

templates/records/group/assign_many_to_group.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ group }} | eRegister
{% endblock title %}


{% block header_nav %}
{% include 'records/group/header_nav_group.html' %}
<script>
    $("#header-nav-assign-many").addClass("active");
</script>
{% endblock header_nav %}


{% block content %}
{% if form.non_field_errors %}
<div class="alert alert-danger">
{{ form.non_field_errors }}
</div>

{% endif %}
<div class="card bg-light mb-3"  style="max-width: 500px;">
    <div class="card-header">Assign students to: {{ group }}</div>
    <div class="card-body">
        <form method="post">{% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endfor %}
            
            <div class="container-fluid text-end px-0 mt-3">
                <button type="submit" name="save" value="save" class="btn btn-success">Assign</button>
                <button type="submit" name="unsafe_add" value="unsafe_add" class="btn btn-outline-success">Assign (skip collissions)</button>
                <a href="{{ object.get_absolute_url }}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

<script>
    $(function () {
        $("#id_date_start").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_date_end").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $('#id_students_to_add').select2();
    });
</script>
{% endblock content %}

templates/records/group/assignment_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Assignment: {{ assignment.student }} | eRegister
{% endblock title %}


{% block header_nav %}
<nav class="nav d-flex flex-column flex-md-row nav-border-red">
    {% if prev %}
        <a class="nav-link text-danger"  href="{{ prev }}"><i class="bi bi-chevron-left"></i>Back</a>
    {% endif %}
</nav>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3"  style="max-width: 500px;">
    <form method="post">{% csrf_token %}
        <div class="card-body">
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <p class="fw-light m-0">Student</p>
            <p class="m-0 mb-3">{{ assignment.student }}</p>
            <p class="fw-light m-0">Group</p>
            <p class="m-0">{{ assignment.group }}</p>
            <hr>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endfor %}
            
            <div class="container-fluid text-end px-0 mt-3">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
                <a href="{{ prev }}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#id_date_start").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_date_end").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $('#id_students_to_add').select2();
    });
</script>
{% endblock content %}

templates/records/group/group_assignments.html
{% extends 'base.html' %}

{% block title %}
    {{ group }} | eRegister
{% endblock title %}


{% block header_nav %}
    {% include 'records/group/header_nav_group.html' %}
    <script>
        $("#header-nav-assignments").addClass("active");
    </script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3">
    <div class="card-header">Current assignments</div>
    <div class="card-body table-responsive">
        <table class="table table-hover">
            <thead>
                <tr style="border-bottom: 1px solid rgb(100, 100, 100);">
                    <th class="col-md-1">#</th>
                    <th>Student</th>
                    <th class="col-md-2">From</th>
                    <th class="col-md-2">To</th>
                    <th class="col-md-1"></th>
                </tr>
            </thead>
            {% for assignment in current_assignments %}
            <tr>
                <td>
                    {{ forloop.counter }}.
                </td>
                <td>
                    {% with assignment.student as student %}
                        <a href="{{ student.get_absolute_url }}" class="text-decoration-none text-dark">
                            {{ student.last_name }} <span class="fw-light">{{ student.first_name }}</span>
                        </a>
                    {% endwith %}
                </td>
                <td>
                    {{ assignment.date_start }}
                </td>
                <td>
                    {{ assignment.date_end }}
                </td>
                <td>
                    {% if perms.records.change_studentgroupassignment %}
                        <a href="{% url 'group:assign-update' assignment.pk %}?prev={{ request.path }}" class="btn btn-outline-primary py-0 my-0">Edit</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="5">
                    <div class="alert alert-warning mb-0">
                        No current assignments found
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
<div class="card bg-light mb-3">
    <div class="card-header">Out of date assignments</div>
    <div class="card-body table-responsive">
        <table class="table table-hover table-borderless table-sm">
            <thead>
                <tr style="border-bottom: 1px solid rgb(100, 100, 100);">
                    <th class="col-md-1">#</th>
                    <th>Student</th>
                    <th class="col-md-2">From</th>
                    <th class="col-md-2">To</th>
                    <th class="col-md-1"></th>
                </tr>
            </thead>
            {% regroup out_of_date_assignments by student as assigments %}
            {% for student in assigments %}
                {% for assignment in student.list %}
                        {% if forloop.first %}
                        <tr>
                            <td>{{ forloop.parentloop.counter }}</td>
                            <td colspan="4">
                                <a href="{{ student.grouper.get_absolute_url }}" class="text-decoration-none text-dark">
                                    {{ student.grouper.last_name }} <span class="fw-light">{{ student.grouper.first_name }}</span>
                                </a>
                            </td>
                        </tr>
                        {% endif %}
                    <tr>
                        <td></td>
                        <td></td>
                        {% if assignment.future %}
                            <td class="text-success">{{ assignment.date_start }}</td>
                            <td class="text-success">{{ assignment.date_end }}</td>
                        {% else %}
                            <td class="text-danger">{{ assignment.date_start }}</td>
                            <td class="text-danger">{{ assignment.date_end }}</td>
                        {% endif %}
                        <td>
                        {% if perms.records.change_studentgroupassignment %}
                            <a href="{% url 'group:assign-update' assignment.pk %}?prev={{ request.path }}" class="btn btn-outline-primary py-0 my-0">Edit</a>
                        {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="5" style="padding: 0; height: 1px !important; border-bottom: 1px solid rgb(220, 220, 220);"></td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="5">
                    <div class="alert alert-warning mt-1 mb-0">
                        No out of date assignments found
                    </div>
                </td>
            </tr>
            {% endfor %}
            
        </table>
    </div>
</div>
{% endblock content %}

templates/records/group/group_courses.html
{% extends 'base.html' %}

{% block title %}
    {{ group }} | eRegister
{% endblock title %}


{% block header_nav %}
    {% include 'records/group/header_nav_group.html' %}
    <script>
        $("#header-nav-courses").addClass("active");
    </script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3">
    <div class="card-header">Courses</div>
    <div class="card-body table-responsive">
        <table class="table table-hover">
            <thead>
                <tr style="border-bottom: 1px solid rgb(100, 100, 100);">
                    <th class="col-md-1">#</th>
                    <th>Course name</th>
                    <th class="col-md-1"></th>
                </tr>
            </thead>
            {% for course in courses %}
            <tr>
                <td>
                    {{ forloop.counter }}.
                </td>
                <td>
                    {{ course.name }}
                </td>
                <td>
                    {% if perms.records.change_course %}
                        <a href="{% url 'group:course-update' course.pk %}" class="btn btn-outline-primary py-0 my-0">Edit</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-warning mb-0">
                        No courses found
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

templates/records/group/header_nav_group.html
<nav class="nav d-flex flex-column flex-md-row">
    <a id="header-nav-detail" class="nav-link fs-5 fw-bold" href="{% url 'group:detail' group.pk %}">{{ group }}</a>
    <a id="header-nav-assignments" class="nav-link" href="{% url 'group:assignments' group.pk %}">Assignments</a>
    <a id="header-nav-courses" class="nav-link" href="{% url 'group:courses' group.pk %}">Courses</a>
    <a id="header-nav-schedule" class="nav-link" href="{% url 'group:schedule' group.pk %}">Schedule</a>
</nav>
<nav class="nav nav-border-red d-flex flex-column flex-md-row">
    {% if perms.records.change_studentgroup %}
    <a class="nav-link text-danger dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" data-bs-auto-close="false" aria-expanded="false">
        <i class="bi bi-pencil"></i> Manage
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li>
            <a id="header-nav-update" href="{% url 'group:update' group.pk %}" class="dropdown-item">Edit information</a>
        </li>
        {% if perms.records.add_studentgroupassignment %}
            <li>
                <a id="header-nav-assign-many" href="{% url 'group:assign-many' group.pk %}" class="dropdown-item"></i>Assign students</a>
            </li>
        {% endif %}
        {% if perms.records.add_course %}
            <li>
                <a id="header-nav-create-course" href="{% url 'group:course-create' group.pk %}" class="dropdown-item"></i>Add course</a>
            </li>
        {% endif %}
        {% if perms.records.add_schedule %}
            <a href="{% url 'schedule:add' group.pk %}?prev={{ request.path }}" class="dropdown-item">Add schedule</a>
        {% endif %}
    </ul>
    {% endif %}
</nav>

templates/records/group/header_nav_list.html
<nav class="nav  d-flex flex-column flex-md-row">
    <a id="header-nav-list" class="nav-link"  href="{% url 'group:list' %}">All groups</a>
    {% if request.user.educated_group %}
        <a id="header-nav-list" class="nav-link"  href="{{ request.user.educated_group.get_absolute_url }}">My group</a>
        
    {% endif %}
</nav>
<nav class="nav nav-border-red d-flex flex-column flex-md-row">
    {% if perms.records.add_studentgroup %}
        <a id="header-nav-create" href="{% url 'group:create' %}" class="nav-link text-danger"><i class="bi bi-plus-lg"></i>New group</a>
    {% endif %}
</nav>