eregister/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard:start')),
    path('dashboard/', include('records.urls.dashboard')),
    path('lesson/', include('records.urls.lesson')),
    path('student/', include('records.urls.student')),
    path('group/', include('records.urls.group')),
    path('auth/', include('records.urls.auth')),
    path('schedule/', include('records.urls.schedule')),
    path('ajax/', include('records.urls.ajax')),
    path('admin/', admin.site.urls),
]

records/models/attendance.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Attendance(models.Model):
    STATUS_PRESENT = 0
    STATUS_LATE = 1
    STATUS_ABSENT = 2

    STATUS_CHOICES = [
        (STATUS_PRESENT, _('Present')),
        (STATUS_LATE, _('Late')),
        (STATUS_ABSENT, _('Absent')),
    ]

    status = models.IntegerField(
        _('Status'),
        blank=False,
        null=False,
        choices=STATUS_CHOICES,
        default=STATUS_PRESENT
    )

    lesson = models.ForeignKey(
        'records.Lesson',
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        related_name='attendances'
    )

    student = models.ForeignKey(
        'records.User',
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        related_name='attendances'
    )

    class Meta:
        verbose_name = _('Attendance')
        verbose_name_plural = _('Attendances')
        unique_together = ['lesson', 'student']
        ordering = ['-lesson__date',
                    'student__last_name', 'student__first_name']

records/models/course.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Course(models.Model):
    name = models.CharField(
        _('Name'),
        max_length=50,
        blank=False,
        null=False,
        help_text=_('Required')
    )

    group = models.ForeignKey(
        'records.StudentGroup',
        verbose_name=_('Student group'),
        blank=False,
        null=False,
        on_delete=models.PROTECT,
        related_name='courses'
    )

    class Meta:
        verbose_name = _('Course')
        verbose_name_plural = _('Courses')
        ordering = ['name']
        unique_together = ['name', 'group']

    def __str__(self):
        # return "%(name)s (%(group)s)" % {
        #     'name': self.name,
        #     'group': self.group.name
        # }
        return str(self.name)

records/models/lesson.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from records.models import attendance
import datetime


class Lesson(models.Model):
    STATUS_PLANNED = 0
    STATUS_REALIZED = 1
    STATUS_CANCELLED = 2
    STATUS_CHOICES = [
        (STATUS_PLANNED, _('Unrealized')),
        (STATUS_REALIZED, _('Realized')),
        (STATUS_CANCELLED, _('Cancelled')),
    ]

    status = models.IntegerField(
        _('Status'),
        blank=False,
        null=False,
        choices=STATUS_CHOICES,
        default=STATUS_PLANNED
    )

    schedule = models.ForeignKey(
        'records.Schedule',
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        verbose_name=_('Schedule entry'),
        related_name='lessons'
    )

    date = models.DateField(
        _('Date'),
        blank=False,
        null=False
    )

    subject = models.CharField(
        _('Subject'),
        blank=True,
        max_length=255,
    )

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')
        ordering = ['-date']
        unique_together = ['schedule', 'date']

    @property
    def is_realized(self):
        return self.status == self.STATUS_REALIZED

    @property
    def is_cancelled(self):
        return self.status == self.STATUS_CANCELLED

    @property
    def is_editable(self):
        return self.date <= datetime.date.today()

    @property
    def short_subject(self):
        subject = self.subject
        return subject if len(subject) < 100 else (subject[:95] + "(...)")

    @classmethod
    def from_dates(cls, schedule, dates):
        """ Bulk create Lessons from dates list"""
        objs = [Lesson(schedule=schedule, date=date) for date in dates]
        Lesson.objects.bulk_create(objs)

    def sync_attendances(self):
        """
        Create Attendances related to Lesson. If lesson is cancelled,
        delete all related attendances
        """

        # delete attendances for cancelled lesson and exit
        if self.is_cancelled:
            self.attendances.all().delete()
            return

        # get list of students by date
        group = self.schedule.course.group
        students = group.get_students_by_date(self.date)

        # create list of students that don't have related Attendance created
        missing_attendances = list(students)
        for att in self.attendances.all():
            if att.student in missing_attendances:
                missing_attendances.remove(att.student)
            else:
                att.delete()

        # create missing Attendances
        for student in missing_attendances:
            attendance.Attendance(lesson=self, student=student).save()

    def get_absolute_url(self):
        return reverse("lesson:update", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.date)

records/models/schedule.py
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from records.models import lesson


class Schedule(models.Model):

    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6
    DAYS_OF_WEEK = [
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Thursday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
        (SUNDAY, _('Sunday')),
    ]

    course = models.ForeignKey(
        'records.Course',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Course')
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_teacher': True},
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Teacher')
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    day_of_week = models.IntegerField(
        _('Day of the week'),
        blank=True,
        choices=DAYS_OF_WEEK
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    period = models.ForeignKey(
        'records.Period',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Period')
    )

    class Meta:
        verbose_name = _('Schedule entry')
        verbose_name_plural = _('Schedule entries')
        ordering = ['date_start']

    def save(self, *args, **kwargs):
        """ Override save method to make it atomic with post_save signal """
        with transaction.atomic():
            super().save(*args, **kwargs)

    def _get_same_time_entries_qs(self):
        """
        Return queryset for schedule entries with same period and weekday,
        and overlaping dates
        """
        qs = Schedule.objects.filter(
            date_start__lte=self.date_end,
            date_end__gte=self.date_start,
            day_of_week=self.day_of_week,
            period=self.period
        ).select_related('teacher', 'course', 'period')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def _get_collisions_by_group(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(course__group=self.course.group)
        return list(qs)

    def _get_collisions_by_teacher(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(teacher=self.teacher)
        return list(qs)

    def _check_collisions(self):
        """
        Check for collisions (if selected teacher or student group
        already have planned lesson at that time)
        """
        raise_error = False
        errors = {}
        qs = self._get_same_time_entries_qs()
        collisions_group = self._get_collisions_by_group(qs)
        collisions_teacher = self._get_collisions_by_teacher(qs)
        error_msg = _("Colliding entries: %(collisions)s")
        if collisions_group:
            errors['course'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_group))
            }
            raise_error = True
        if collisions_teacher:
            errors['teacher'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_teacher))
            }
            raise_error = True

        if raise_error:
            raise ValidationError(errors)

    def clean(self) -> None:
        super().clean()
        # check if ending date isn't earlier than starting date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _("Ending date can't "
                              "be earlier than starting date.")
            })

        # limit schedule length
        dates_diff = self.date_end - self.date_start
        if dates_diff.days > 365:
            raise ValidationError({
                'date_end': _("Schedule length can't exceed 365 days.")
            })

        self.day_of_week = self.date_start.weekday()
        self._check_collisions()

    @property
    def is_editable(self):
        """
        Check for related Lessons with realized or cancelled status.
        Return False if any exist, True otherwise. Used in Schedule
        update view to limit modifiable fields.
        """
        qs = self.lessons.exclude(status=lesson.Lesson.STATUS_PLANNED)
        return False if qs.exists() else True

    def __str__(self) -> str:
        return "{}, {}, {} ({}, {} - {})".format(
            self.course,
            self.course.group,
            self.teacher,
            self.period,
            self.date_start,
            self.date_end
        )

    def get_absolute_url(self):
        kwargs = {
            'pk': self.course.group.pk,
            'date': self.date_start,
            'full_week': 1,
        }
        return reverse_lazy("group:schedule-specified", kwargs=kwargs)

records/forms/attendance.py
from django.forms import modelformset_factory, ModelForm, RadioSelect
from records.models import Attendance


class AttendanceForm(ModelForm):
    class Meta:
        model = Attendance
        fields = ['status']
        widgets = {
            'status': RadioSelect(attrs={'class': 'form-check-input me-1'}),
        }


AttendanceFormSet = modelformset_factory(
    Attendance,
    form=AttendanceForm,
    extra=0,
)

records/forms/group.py
from records.models.course import Course
from django import forms
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from records.utils.user import get_students_without_group
from records.models import StudentGroup
from datetime import date

User = get_user_model()


class GroupCreateForm(forms.ModelForm):
    """
    'educator' field is limited to teachers without StudentGroup assigned.
    """
    educator = forms.ModelChoiceField(
        queryset=User.objects.filter(
            educated_group=None, is_teacher=True),
        required=True
    )

    class Meta:
        model = StudentGroup
        fields = ['name', 'educator']


class GroupUpdateForm(forms.ModelForm):
    """
    'educator' field is limited to teachers without StudentGroup assigned
    and current group's educator.
    """
    educator = forms.ModelChoiceField(
        queryset=None,
        required=True
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['educator'].queryset = User.objects.filter(
            Q(educated_group=None, is_teacher=True)
            | Q(pk=self.instance.educator.pk)
        )
        self.fields['educator'].initial = self.instance.educator

    class Meta:
        model = StudentGroup
        fields = ['name', 'educator']


class AssignManyToGroupForm(forms.Form):
    """
    Assign multiple students to group.
    Limit select choices to students without actual assignment.
    """
    students_to_add = forms.ModelMultipleChoiceField(
        queryset=get_students_without_group(),
        label=_('Students'),
        help_text=_(
            "Only students currently not assigned to any group are shown. "
            "Students with up-to-date assignment, "
            "can be edited from their profile."
        ),
        required=True,
    )

    date_start = forms.DateField(
        label=_('Start date'),
        required=True,
    )

    date_end = forms.DateField(
        label=_('End date'),
        required=True,
    )

    def clean(self):
        cleaned_data = super().clean()

        d_start = cleaned_data.get('date_start')
        d_end = cleaned_data.get('date_end')
        if d_end < d_start:
            raise ValidationError({
                'date_end': _(
                    "End date can't be earlier than start date."
                )
            })


class CourseCreateForm(forms.ModelForm):
    group = forms.ModelChoiceField(
        queryset=StudentGroup.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    class Meta:
        model = Course
        fields = '__all__'


class GroupDateScheduleForm(forms.Form):
    """ Used for filtering group's schedule on group's info page """
    date = forms.DateField(
        initial=date.today,
        required=True
    )

    full_week = forms.BooleanField(
        initial=True,
        label=_('Show whole week'),
        required=False
    )

records/forms/mark.py
from records.models import Mark, User, Course
from django import forms


class MarkUpdateForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ['symbol']


class MarkCreateForm(forms.ModelForm):
    """
    Form to create Mark, need provided students queryset as argument,
    and course and teacher in initial dict.
    """
    class Meta:
        model = Mark
        fields = '__all__'

    student = forms.ModelChoiceField(
        queryset=None,
        required=True
    )

    teacher = forms.ModelChoiceField(
        queryset=User.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    course = forms.ModelChoiceField(
        queryset=Course.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    def __init__(self, *args, students, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student'].queryset = students

records/forms/student.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import fields
from records.models import StudentGroupAssignment

User = get_user_model()


class StudentCreateForm(forms.ModelForm):
    """
    Form used to create new student.
    Account is created without password. It can be generated in right view.
    """

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'birth_date', 'address',
                  'zip_code', 'city', 'phone', 'email']
        widgets = {
            'birth_date': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'}),
        }


class AssignToGroupForm(forms.ModelForm):
    student = forms.ModelChoiceField(
        queryset=User.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    class Meta:
        model = StudentGroupAssignment
        fields = '__all__'

records/views/dashboard.py
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from records.utils.schedule import get_lessons_table


class DashboardRedirectView(LoginRequiredMixin, RedirectView):
    """
    Redirect user's with teacher status to teacher dashboard,
    student to student dashboard.
    """

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_teacher:
            return reverse_lazy('dashboard:teacher')
        else:
            pass  # TODO: student's dashboard


class TeacherDashboardView(LoginRequiredMixin, UserPassesTestMixin,
                           TemplateView):
    template_name = "records/dashboard/teacher_dashboard.html"

    def test_func(self):
        return self.request.user.is_teacher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['table'] = get_lessons_table(self.request.user)
        return context

records/views/mixins.py
class PrevURLMixin:
    """
    Gets previous site url from GET parameters and adds to context data
    if it's present.
    """
    prev_url = None

    def dispatch(self, request, *args, **kwargs):
        self.prev_url = request.GET.get('prev', None)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        if self.prev_url:
            kwargs['prev'] = self.prev_url
        return super().get_context_data(**kwargs)

templates/records/schedule/group_timetable.html
{% extends 'base.html' %} 
{% load widget_tweaks %}

{% block title %}
    Schedule | eRegister
{% endblock title %}

{% block header_nav %}
{% include 'records/schedule/header_nav.html' %}
<script>
    $("#header-nav-group").addClass("active");
</script>
{% endblock header_nav %}

{% block content %}
<div class="card bg-light mb-3">
    <a class="text-decoration-none" data-bs-toggle="collapse" href="#collapseFilter" role="button" aria-expanded="false" aria-controls="collapseFilter">
        <div class="card-header">
            Filter
        </div>
    </a>
    <div id="collapseFilter" class="card-body collapse show">
        <form method="post" class="row">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="col-sm-6 mb-3">
                <label for="{{ form.teacher.id_for_label }}">{{ form.group.label }}</label>
                {{ form.group|add_class:'form-control' }}
                <div class="form-text">
                    {{ form.group.help_text }}
                </div>
                {% for error in form.group.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="col-sm-6 mb-3">
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
                {{ form.date|add_class:'form-control' }}
                <div class="form-text">
                    {{ form.date.help_text }}
                </div>
                {% for error in form.date.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="container-fluid text-end px-2">
                <div class="form-check d-inline-block me-3">
                    {{ form.full_week|add_class:'form-check-input' }}
                    <label class="form-check-label" for="{{ form.full_week.id_for_label }}">{{ form.full_week.label }}</label>
                    <div class="form-text">
                        {{ form.full_week.help_text }}
                    </div>
                </div>
                <button type="submit" name="show" value="show" class="btn btn-primary">Show</button>
            </div>
        </form>
    </div>
</div>

{% if timetable %} 
<div class="card bg-light mb-3 table-responsive">
    {% include 'includes/timetable.html' %}
</div>
{% endif %}

<script>

    $(function () {
            $('#id_group').select2();
            $("#id_date").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "-2:+2",
                dateFormat: "yy-mm-dd",
                firstDay: 1
            });
        });
</script>
{% endblock content %}

templates/records/schedule/header_nav.html
<nav class="nav  d-flex flex-column flex-md-row">
    <a id="header-nav-my" class="nav-link"  href="{% url 'schedule:timetable-my' %}">My schedule</a>
    <a id="header-nav-teacher" class="nav-link"  href="{% url 'schedule:timetable-teacher' %}">Teacher's schedule</a>
    <a id="header-nav-group" class="nav-link"  href="{% url 'schedule:timetable-group' %}">Group's schedule</a>
</nav>

templates/records/schedule/schedule_add.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Add schedule | eRegister
{% endblock title %}


{% block header_nav %}
<nav class="nav d-flex flex-column flex-md-row">
    {% if prev %}
        <a id="header-nav-list" class="nav-link text-danger" href="{{ prev }}"><i class="bi bi-chevron-left"></i>Back</a>
    {% endif %}
</nav>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3" style="max-width: 500px;">
    <div class="card-header">
        {{ group }}
    </div>
    <div class="card-body">
        <form method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endfor %}
            <div class="container-fluid text-end px-0 mt-3">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(function () {
        $('#id_teacher').select2();

        $("#id_date_start").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-1:+1",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_date_end").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-1:+1",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_day_of_week").prop("disabled", true);
    });

    $("#id_date_start").change(function(){
        date = new Date(this.value);
        day_of_week = date.getDay() - 1;
        if (day_of_week == -1) day_of_week = 6;
        $("#id_day_of_week").val(day_of_week);
    });
</script>
{% endblock content %}

templates/records/schedule/schedule_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    Edit schedule | eRegister
{% endblock title %}


{% block header_nav %}
<nav class="nav d-flex flex-column flex-md-row">
    {% if prev %}
        <a id="header-nav-list" class="nav-link text-danger" href="{{ prev }}"><i class="bi bi-chevron-left"></i>Back</a>
    {% endif %}
</nav>
{% endblock header_nav %}


{% block content %}
{% if not schedule.is_editable %}
    <div class="alert alert-warning">
        Selected schedule has realized or cancelled lessons - only starting and ending date is modifiable.
    </div>
{% endif %}
<div class="card bg-light mb-3" style="max-width: 500px;">
    <div class="card-header">
        Edit schedule
    </div>
    <div class="card-body">
        <form method="post">{% csrf_token %}
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endfor %}
            <div class="container-fluid text-end px-0 mt-3">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
            </div>
        </form>
    </div>
</div>

<script>
    $(function () {
        $('#id_teacher').select2();

        $("#id_date_start").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-1:+1",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_date_end").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-1:+1",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_day_of_week").prop("disabled", true);
    });

    $("#id_date_start").change(function(){
        date = new Date(this.value);
        day_of_week = date.getDay() - 1;
        if (day_of_week == -1) day_of_week = 6;
        $("#id_day_of_week").val(day_of_week);
    });
</script>
{% endblock content %}

templates/records/schedule/teacher_timetable.html
{% extends 'base.html' %} 
{% load widget_tweaks %}

{% block title %}
    Schedule | eRegister
{% endblock title %}

{% block header %}
    Schedule
{% endblock header %}

{% block header_nav %}
{% endblock header_nav %}

{% block content %}
<div class="card bg-light mb-3">
    <form method="post">{% csrf_token %}
        <div class="card-body row">
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="col-sm-6 mb-3">
                <label for="{{ form.teacher.id_for_label }}">{{ form.teacher.label }}</label>
                {{ form.teacher|add_class:'form-control' }}
                <div class="form-text">
                    {{ form.teacher.help_text }}
                </div>
                {% for error in form.teacher.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="col-sm-6 mb-3">
                <label for="{{ form.date.id_for_label }}">{{ form.date.label }}</label>
                {{ form.date|add_class:'form-control' }}
                <div class="form-text">
                    {{ form.date.help_text }}
                </div>
                {% for error in form.date.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            <div class="container-fluid text-end px-2">
                <div class="form-check d-inline-block me-3">
                    {{ form.full_week|add_class:'form-check-input' }}
                    <label class="form-check-label" for="{{ form.full_week.id_for_label }}">{{ form.full_week.label }}</label>
                    <div class="form-text">
                        {{ form.full_week.help_text }}
                    </div>
                </div>
                <button type="submit" name="show" value="show" class="btn btn-primary">Show</button>
            </div>
        </div>
    </form>
</div>

{% if timetable %} 
<div class="card bg-light mb-3 table-responsive">
    {% include 'includes/timetable.html' %}
</div>
{% endif %}

<script>

    $( function() {
      $( "#id_date" ).datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "-2:+2",
        dateFormat: "yy-mm-dd",
        firstDay: 1
      });
    } );
</script>
{% endblock content %}