eregister/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard:start')),
    path('dashboard/', include('records.urls.dashboard')),
    path('lesson/', include('records.urls.lesson')),
    path('student/', include('records.urls.student')),
    path('group/', include('records.urls.group')),
    path('auth/', include('records.urls.auth')),
    path('schedule/', include('records.urls.schedule')),
    path('ajax/', include('records.urls.ajax')),
    path('admin/', admin.site.urls),
]

records/models/schedule.py
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from records.models import lesson


class Schedule(models.Model):

    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6
    DAYS_OF_WEEK = [
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Thursday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
        (SUNDAY, _('Sunday')),
    ]

    course = models.ForeignKey(
        'records.Course',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Course')
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_teacher': True},
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Teacher')
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    day_of_week = models.IntegerField(
        _('Day of the week'),
        blank=True,
        choices=DAYS_OF_WEEK
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    period = models.ForeignKey(
        'records.Period',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Period')
    )

    class Meta:
        verbose_name = _('Schedule entry')
        verbose_name_plural = _('Schedule entries')
        ordering = ['date_start']

    def save(self, *args, **kwargs):
        """ Override save method to make it atomic with post_save signal """
        with transaction.atomic():
            super().save(*args, **kwargs)

    def _get_same_time_entries_qs(self):
        """
        Return queryset for schedule entries with same period and weekday,
        and overlaping dates
        """
        qs = Schedule.objects.filter(
            date_start__lte=self.date_end,
            date_end__gte=self.date_start,
            day_of_week=self.day_of_week,
            period=self.period
        ).select_related('teacher', 'course', 'period')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def _get_collisions_by_group(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(course__group=self.course.group)
        return list(qs)

    def _get_collisions_by_teacher(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(teacher=self.teacher)
        return list(qs)

    def _check_collisions(self):
        """
        Check for collisions (if selected teacher or student group
        already have planned lesson at that time)
        """
        raise_error = False
        errors = {}
        qs = self._get_same_time_entries_qs()
        collisions_group = self._get_collisions_by_group(qs)
        collisions_teacher = self._get_collisions_by_teacher(qs)
        error_msg = _("Colliding entries: %(collisions)s")
        if collisions_group:
            errors['course'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_group))
            }
            raise_error = True
        if collisions_teacher:
            errors['teacher'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_teacher))
            }
            raise_error = True

        if raise_error:
            raise ValidationError(errors)

    def clean(self) -> None:
        super().clean()
        # check if ending date isn't earlier than starting date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _("Ending date can't "
                              "be earlier than starting date.")
            })

        # limit schedule length
        dates_diff = self.date_end - self.date_start
        if dates_diff.days > 365:
            raise ValidationError({
                'date_end': _("Schedule length can't exceed 365 days.")
            })

        self.day_of_week = self.date_start.weekday()
        self._check_collisions()

    @property
    def is_editable(self):
        """
        Check for related Lessons with realized or cancelled status.
        Return False if any exist, True otherwise. Used in Schedule
        update view to limit modifiable fields.
        """
        qs = self.lessons.exclude(status=lesson.Lesson.STATUS_PLANNED)
        return False if qs.exists() else True

    def __str__(self) -> str:
        return "{}, {}, {} ({}, {} - {})".format(
            self.course,
            self.course.group,
            self.teacher,
            self.period,
            self.date_start,
            self.date_end
        )

    def get_absolute_url(self):
        kwargs = {
            'pk': self.course.group.pk,
            'date': self.date_start,
            'full_week': 1,
        }
        return reverse_lazy("group:schedule-specified", kwargs=kwargs)

records/models/studentgroup.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()


class StudentGroup(models.Model):
    """
    Group of Users without teacher status.
    - StudentGroup_obj.educator - User object set as educator
    """
    class Meta:
        verbose_name = _('Student group')
        verbose_name_plural = _('Student groups')
        ordering = ['name', ]

    name = models.CharField(
        _('Name'),
        blank=False,
        unique=True,
        max_length=30,
    )

    # Educator responsible for the group.
    # Limit choices to Users with is_teacher set to True
    educator = models.OneToOneField(
        verbose_name=_('Educator'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': True},
        related_name='educated_group'
    )

    def get_assignments_by_date(self, date=None):
        """
        Return queryset of assignments to the group for specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        qs = self.assignments.filter(
            date_start__lte=date,
            date_end__gte=date,
        ).select_related('student')
        return qs

    def get_all_assignments(self):
        """
        Return queryset for all assignemts to the group,
        including out of date assignments
        """
        qs = self.assignments.select_related('student')
        return qs

    def get_students_by_date(self, date=None):
        """
        Return queryset of students assigned to the group on specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        assignments = self.get_assignments_by_date(date)
        current_students = User.objects.filter(
            assignments__in=assignments)
        return current_students

    def get_all_students(self):
        """
        Return queryset of all students assigned to the group,
        including out of date assignments
        """
        all_students = User.objects.filter(
            assignments__in=self.assignments.all()
        ).distinct()
        return all_students

    @property
    def current_assignments(self): return self.get_assignments_by_date()

    @property
    def current_students(self): return self.get_students_by_date()

    def get_absolute_url(self):
        return reverse_lazy('group:detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return str(self.name)


class StudentGroupAssignment(models.Model):
    class Meta:
        verbose_name = _('Group assignment')
        verbose_name_plural = _('Group assignments')
        ordering = ['student__last_name', 'student__first_name', 'date_start']

    student = models.ForeignKey(
        verbose_name=_('Student'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': False},
        related_name='assignments'
    )

    group = models.ForeignKey(
        verbose_name=_('Student group'),
        to=StudentGroup,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        related_name='assignments'
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    def _get_colliding_assignments(self):
        qs = StudentGroupAssignment.objects.filter(
            student=self.student,
            date_start__lte=self.date_end,
            date_end__gte=self.date_start
        ).select_related('student', 'group')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def clean(self):
        super().clean()

        # check if ending date is not earlier than start date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _(
                    "End date can't be earlier than start date."
                )
            })
        colliding_assignments = list(self._get_colliding_assignments())
        if colliding_assignments:
            raise ValidationError(
                _("Colliding assigments for %(student)s: %(collisions)s"),
                params={
                    'student': str(self.student),
                    'collisions': ", ".join(map(str, colliding_assignments)),
                }
            )

    def __str__(self):
        return "{} ({} - {})".format(
            self.group, self.date_start, self.date_end
        )

records/models/user.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.urls import reverse
import datetime


class User(AbstractUser):
    """
    Substitute for built-in User model, with required first/last name
    and autogenerated username.
    Additional bool is_teacher field.
    Additional optional fields:
        -birth_date -> Date
        -address -> char
        -zip_code -> char
        -city -> char
        -phone_number -> char
        -student_group -> ForeignKey(StudentGroup)
    New permissions: add_student, view_student, change_student, delete_student,
        reset_student_password
    """
    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['last_name', 'first_name']
        permissions = [
            ('add_student', _('Can add Student')),
            ('view_student', _('Can view Student')),
            ('change_student', _('Can change Student')),
            ('delete_student', _('Can delete Student')),
            ('reset_student_password', _('Can reset Student\'s password')),
        ]

    # Make username unrequired. If left blank during creation/editing,
    # username will be generated by generate_username() called by
    # pre_save signal.
    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Letters, digits and @/./+/-/_ only. '
            'Autogenerated if left blank.'),
        validators=[AbstractUser.username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
        blank=True,
    )
    first_name = models.CharField(
        _('first name'), max_length=150, blank=False, null=False,
        help_text='Required.')
    last_name = models.CharField(
        _('last name'), max_length=150, blank=False, null=False,
        help_text='Required.')

    birth_date = models.DateField(
        _('Birth date'), blank=True, null=True)

    address = models.CharField(
        _('Address'), max_length=50, blank=True, null=True)
    zip_code = models.CharField(
        _('ZIP code'), max_length=10, blank=True, null=True)
    city = models.CharField(
        _('City'), max_length=50, blank=True, null=True)
    phone = models.CharField(
        _('Phone number'), max_length=15, blank=True, null=True)

    is_teacher = models.BooleanField(default=False)

    # Fields required during createsuperuser
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    @property
    def is_student(self) -> bool:
        return not self.is_teacher

    @property
    def is_educator(self) -> bool:
        return hasattr(self, 'educated_group')

    def get_current_assignment(self):
        today = datetime.date.today()
        qs = self.assignments.filter(
            date_start__lte=today,
            date_end__gte=today,
        ).select_related('group')
        return qs.first()

    @property
    def student_group(self):
        """Return currently assigned student group or None"""
        assign = self.get_current_assignment()
        if assign:
            return assign.group
        return None

    def clean(self) -> None:
        """
        Check if user is designated as group educator,
        before removing teacher status.
        """
        super().clean()
        if not self.is_teacher and self.is_educator:
            err_msg = _(
                "User is designated as educator of group {student_group}. "
                "Can\'t remove teacher status."
            ).format(student_group=self.educated_group)

            raise ValidationError(
                {'student_group': err_msg}
            )

    def get_absolute_url(self):
        return reverse("student:detail", kwargs={"pk": self.pk})

    def get_full_name(self):
        full_name = '%s %s' % (self.last_name, self.first_name)
        return full_name.strip()

    def __str__(self) -> str:
        """Return full name instead of username"""
        return self.get_full_name()

records/forms/attendance.py
from django.forms import modelformset_factory, ModelForm, RadioSelect
from records.models import Attendance


class AttendanceForm(ModelForm):
    class Meta:
        model = Attendance
        fields = ['status']
        widgets = {
            'status': RadioSelect(attrs={'class': 'form-check-input me-1'}),
        }


AttendanceFormSet = modelformset_factory(
    Attendance,
    form=AttendanceForm,
    extra=0,
)

records/forms/student.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import fields
from records.models import StudentGroupAssignment

User = get_user_model()


class StudentCreateForm(forms.ModelForm):
    """
    Form used to create new student.
    Account is created without password. It can be generated in right view.
    """

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'birth_date', 'address',
                  'zip_code', 'city', 'phone', 'email']
        widgets = {
            'birth_date': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'}),
        }


class AssignToGroupForm(forms.ModelForm):
    student = forms.ModelChoiceField(
        queryset=User.objects,
        disabled=True,
        widget=forms.HiddenInput()
    )

    class Meta:
        model = StudentGroupAssignment
        fields = '__all__'

records/views/dashboard.py
from django.views.generic import TemplateView, RedirectView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from records.utils.schedule import get_lessons_table


class DashboardRedirectView(LoginRequiredMixin, RedirectView):
    """
    Redirect user's with teacher status to teacher dashboard,
    student to student dashboard.
    """

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_teacher:
            return reverse_lazy('dashboard:teacher')
        else:
            pass  # TODO: student's dashboard


class TeacherDashboardView(LoginRequiredMixin, UserPassesTestMixin,
                           TemplateView):
    template_name = "records/dashboard/teacher_dashboard.html"

    def test_func(self):
        return self.request.user.is_teacher

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['table'] = get_lessons_table(self.request.user)
        return context

records/views/mixins.py
class PrevURLMixin:
    """
    Gets previous site url from GET parameters and adds to context data
    if it's present.
    """
    prev_url = None

    def dispatch(self, request, *args, **kwargs):
        self.prev_url = request.GET.get('prev', None)
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        if self.prev_url:
            kwargs['prev'] = self.prev_url
        return super().get_context_data(**kwargs)

templates/records/student/assign_to_group.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ student }} | eRegister
{% endblock title %}

{% block header %}
    {{ student }}
{% endblock header %}

{% block header_nav %}
{% include 'records/student/header_nav_student.html' %}
<script>
    $("#header-nav-assign").addClass("active");
</script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3"  style="max-width: 500px;">
    <form method="post">{% csrf_token %}
        <div class="card-body">
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <p class="fw-light m-0">Student</p>
            <p class="m-0 mb-3">{{ student }}</p>
            <hr>
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                <div class="form-text">
                    {{ field.help_text }}
                </div>
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            {% endfor %}
            
            <div class="container-fluid text-end px-0 mt-3">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
            </div>
        </div>
    </form>
</div>
<script>
    $(function () {
        $("#id_date_start").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
        $("#id_date_end").datepicker({
            changeMonth: true,
            changeYear: true,
            yearRange: "-3:+3",
            dateFormat: "yy-mm-dd",
            firstDay: 1
        });
    });
</script>
{% endblock content %}

templates/records/student/header_nav_list.html
<nav class="nav  d-flex flex-column flex-md-row">
    <a id="header-nav-list" class="nav-link" href="{% url 'student:list' %}">All students</a>
</nav>
<nav class="nav nav-border-red d-flex flex-column flex-md-row">
    {% if perms.records.add_student %}
        <a id="header-nav-create" href="{% url 'student:create' %}" class="nav-link  text-danger"><i class="bi bi-plus-lg"></i>Add student</a>
    {% endif %}
</nav>

templates/records/student/header_nav_student.html
<nav class="nav d-flex flex-column flex-md-row">
    <a id="header-nav-detail" class="nav-link fs-5 fw-bold" href="{{ student.get_absolute_url }}">{{ student }}</a>
    <a id="header-nav-assignments" class="nav-link" href="{% url 'student:assignments' student.pk %}">Groups</a>
    <a id="header-nav-marks" class="nav-link" href="{% url 'student:marks' student.pk %}">Marks</a>
    <a class="nav-link" href="#">Attendance</a>
</nav>
<nav class="nav nav-border-red d-flex flex-column flex-md-row">
    {% if perms.records.add_studentgroupassignment %}
        <a id="header-nav-assign" href="{% url 'student:assign' student.pk %}" class="nav-link text-danger"><i class="bi bi-person-plus"></i>Assign to a group</span></a>
    {% endif %}
    {% if perms.records.change_student %}
        <a id="header-nav-update" href="{% url 'student:update' student.pk %}" class="nav-link text-danger" ><i class="bi bi-pencil"></i>Edit</a>
    {% endif %}
</nav>

templates/records/student/student_assignments.html
{% extends 'base.html' %}

{% block title %}
    {{ student }} | eRegister
{% endblock title %}

{% block header %}
    {{ student }}
{% endblock header %}

{% block header_nav %}
    {% include 'records/student/header_nav_student.html' %}
    <script>
        $("#header-nav-assignments").addClass("active");
    </script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3">
    <div class="card-header">Current assignment</div>
    <div class="card-body">
        {% if current_assignment %}
            <div class="row">
                <div class="col-lg-4">
                    <p class="fw-light m-0">Group</p>
                    <p class="m-0">
                        <a href="{{ current_assignment.group.get_absolute_url }}" class="text-decoration-none">
                            <i class="bi bi-link-45deg"></i> {{ current_assignment.group }}&nbsp;
                        </a>
                    </p>
                </div>
                <div class="col-lg-4">

                    <p class="fw-light m-0">From</p>
                    <p class="m-0">{{ current_assignment.date_start }}</p>
                </div>
                <div class="col-lg-4">
                    <p class="fw-light m-0">To</p>
                    <p class="m-0">{{ current_assignment.date_end }}</p>
                </div>
                <div class="container-fluid text-end">
                    <a href="{% url 'group:assign-update' current_assignment.pk %}?prev={{ request.path }}" class="btn btn-outline-primary">Edit</a>
                </div>
            </div>
        {% else %}
            <div class="alert alert-warning mb-0 mt-1">
                Currently not assigned to any group.
            </div>    
        {% endif %}
        
    </div>
</div>
<div class="card bg-light mb-3">
    <div class="card-header">Out of date assignments</div>
    <div class="card-body table-responsive">
        <table class="table table-hover table-borderless table-sm">
            <thead>
                <tr style="border-bottom: 1px solid rgb(100, 100, 100);">
                    <th class="col-md-1">#</th>
                    <th>Group</th>
                    <th class="col-md-2">From</th>
                    <th class="col-md-2">To</th>
                    <th class="col-md-1"></th>
                </tr>
            </thead>
            {% for assignment in out_of_date_assignments %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{{ assignment.group.get_absolute_url }}" class="text-decoration-none  text-dark">
                            {{ assignment.group }}
                        </a>
                    </td>
                    {% if assignment.future %}
                        <td class="text-success">{{ assignment.date_start }}</td>
                        <td class="text-success">{{ assignment.date_end }}</td>
                    {% else %}
                        <td class="text-danger">{{ assignment.date_start }}</td>
                        <td class="text-danger">{{ assignment.date_end }}</td>
                    {% endif %}
                
                    <td>
                    {% if perms.records.change_studentgroupassignment %}
                        <a href="{% url 'group:assign-update' assignment.pk %}?prev={{ request.path }}" class="btn btn-outline-primary py-0 my-0">Edit</a>
                    {% endif %}
                    </td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="5">
                    <div class="alert alert-warning mt-1 mb-0">
                        No out of date assignments found
                    </div>
                </td>
            </tr>
            {% endfor %}
            
        </table>
    </div>
</div>
{% endblock content %}

templates/records/student/student_create.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    New student | eRegister
{% endblock title %}

{% block header %}
    New student
{% endblock header %}

{% block header_nav %}
{% include 'records/student/header_nav_list.html' %}
<script>
    $("#header-nav-create").addClass("active");
</script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3">
    <form method="post">{% csrf_token %}
        <div class="card-body">
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="row">
                {% for field in form.visible_fields %}
                    <div class="col-xl-6">
                        <div class="row mb-3">
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-lg-4 col-form-label">{{ field.label }}</label>
                            <div class="col-md-8 col-lg-8">
                                {{ field|add_class:'form-control' }}
                                <div class="form-text">
                                    {{ field.help_text }}
                                </div>
                                {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            
            <div class="container-fluid text-end px-0">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
                <button type="submit" name="save_and_add_next" value="save_and_add_next" class="btn btn-outline-success">Save and add next</button>
            </div>
        </div>
    </form>
</div>

<script>
    $( function() {
      $( "#id_birth_date" ).datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "1950:-5",
        defaultDate: "-5y",
        dateFormat: "yy-mm-dd",
        firstDay: 1
      });
    } );
</script>
{% endblock content %}

templates/records/student/student_list.html
{% extends 'base.html' %}

{% block title %}
    Students | eRegister
{% endblock title %}

{% block header %}
    Students
{% endblock header %}

{% block header_nav %}
{% include 'records/student/header_nav_list.html' %}
<script>
    $("#header-nav-list").addClass("active");
</script>
{% endblock header_nav %}


{% block content %}
{% include 'includes/pagination.html' %}
<div class="card bg-light my-3">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">Last name</th>
                        <th scope="col">First name</th>
                        <th scope="col">Group</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in students %}
                    <tr class="align-middle">
                        <th scope="row">
                            <a href="{{ student.get_absolute_url }}" class="text-decoration-none">{{ student.last_name }}</a>
                        </th>
                        <td>{{ student.first_name }}</td>
                        <td>{{ student.student_group|default_if_none:"" }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% include 'includes/pagination.html' %}
{% endblock content %}

templates/records/student/student_update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    {{ object }} | eRegister
{% endblock title %}

{% block header %}
    {{ object }}
{% endblock header %}

{% block header_nav %}
{% include 'records/student/header_nav_student.html' %}
<script>
    $("#header-nav-update").addClass("active");
</script>
{% endblock header_nav %}


{% block content %}
<div class="card bg-light mb-3">
    <form method="post">{% csrf_token %}
        <div class="card-body">
            {{ form.non_field_errors }}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="row">
                {% for field in form.visible_fields %}
                    <div class="col-xl-6">
                        <div class="row mb-3">
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-lg-3 col-form-label">{{ field.label }}</label>
                            <div class="col-md-8 col-lg-9">
                                {{ field|add_class:'form-control' }}
                                <div class="form-text">
                                    {{ field.help_text }}
                                </div>
                                {% for error in field.errors %}
                                <span class="help-block">{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="container-fluid text-end px-0">
                <button type="submit" name="save" value="save" class="btn btn-success">Save</button>
                <button type="submit" name="save_and_continue" value="save_and_continue" class="btn btn-outline-success">Save and continue editing</button>
                <a href="{{ student.get_absolute_url }}" class="btn btn-outline-danger">Cancel</a>
            </div>
        </div>
    </form>
</div>


<script>
    $( function() {
      $( "#id_birth_date" ).datepicker({
        changeMonth: true,
        changeYear: true,
        yearRange: "1950:-5",
        defaultDate: "-5y",
        dateFormat: "yy-mm-dd",
        firstDay: 1
      });
    } );
</script>
{% endblock content %}