eregister/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard:start')),
    path('dashboard/', include('records.urls.dashboard')),
    path('lesson/', include('records.urls.lesson')),
    path('student/', include('records.urls.student')),
    path('group/', include('records.urls.group')),
    path('auth/', include('records.urls.auth')),
    path('schedule/', include('records.urls.schedule')),
    path('ajax/', include('records.urls.ajax')),
    path('admin/', admin.site.urls),
]

records/models/lesson.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from records.models import attendance
import datetime


class Lesson(models.Model):
    STATUS_PLANNED = 0
    STATUS_REALIZED = 1
    STATUS_CANCELLED = 2
    STATUS_CHOICES = [
        (STATUS_PLANNED, _('Unrealized')),
        (STATUS_REALIZED, _('Realized')),
        (STATUS_CANCELLED, _('Cancelled')),
    ]

    status = models.IntegerField(
        _('Status'),
        blank=False,
        null=False,
        choices=STATUS_CHOICES,
        default=STATUS_PLANNED
    )

    schedule = models.ForeignKey(
        'records.Schedule',
        on_delete=models.CASCADE,
        blank=False,
        null=False,
        verbose_name=_('Schedule entry'),
        related_name='lessons'
    )

    date = models.DateField(
        _('Date'),
        blank=False,
        null=False
    )

    subject = models.CharField(
        _('Subject'),
        blank=True,
        max_length=255,
    )

    class Meta:
        verbose_name = _('Lesson')
        verbose_name_plural = _('Lessons')
        ordering = ['-date']
        unique_together = ['schedule', 'date']

    @property
    def is_realized(self):
        return self.status == self.STATUS_REALIZED

    @property
    def is_cancelled(self):
        return self.status == self.STATUS_CANCELLED

    @property
    def is_editable(self):
        return self.date <= datetime.date.today()

    @property
    def short_subject(self):
        subject = self.subject
        return subject if len(subject) < 100 else (subject[:95] + "(...)")

    @classmethod
    def from_dates(cls, schedule, dates):
        """ Bulk create Lessons from dates list"""
        objs = [Lesson(schedule=schedule, date=date) for date in dates]
        Lesson.objects.bulk_create(objs)

    def sync_attendances(self):
        """
        Create Attendances related to Lesson. If lesson is cancelled,
        delete all related attendances
        """

        # delete attendances for cancelled lesson and exit
        if self.is_cancelled:
            self.attendances.all().delete()
            return

        # get list of students by date
        group = self.schedule.course.group
        students = group.get_students_by_date(self.date)

        # create list of students that don't have related Attendance created
        missing_attendances = list(students)
        for att in self.attendances.all():
            if att.student in missing_attendances:
                missing_attendances.remove(att.student)
            else:
                att.delete()

        # create missing Attendances
        for student in missing_attendances:
            attendance.Attendance(lesson=self, student=student).save()

    def get_absolute_url(self):
        return reverse("lesson:update", kwargs={"pk": self.pk})

    def __str__(self):
        return str(self.date)

records/models/schedule.py
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.urls.base import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from records.models import lesson


class Schedule(models.Model):

    MONDAY = 0
    TUESDAY = 1
    WEDNESDAY = 2
    THURSDAY = 3
    FRIDAY = 4
    SATURDAY = 5
    SUNDAY = 6
    DAYS_OF_WEEK = [
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Thursday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
        (SUNDAY, _('Sunday')),
    ]

    course = models.ForeignKey(
        'records.Course',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Course')
    )

    teacher = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_teacher': True},
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Teacher')
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    day_of_week = models.IntegerField(
        _('Day of the week'),
        blank=True,
        choices=DAYS_OF_WEEK
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    period = models.ForeignKey(
        'records.Period',
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        verbose_name=_('Period')
    )

    class Meta:
        verbose_name = _('Schedule entry')
        verbose_name_plural = _('Schedule entries')
        ordering = ['date_start']

    def save(self, *args, **kwargs):
        """ Override save method to make it atomic with post_save signal """
        with transaction.atomic():
            super().save(*args, **kwargs)

    def _get_same_time_entries_qs(self):
        """
        Return queryset for schedule entries with same period and weekday,
        and overlaping dates
        """
        qs = Schedule.objects.filter(
            date_start__lte=self.date_end,
            date_end__gte=self.date_start,
            day_of_week=self.day_of_week,
            period=self.period
        ).select_related('teacher', 'course', 'period')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def _get_collisions_by_group(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(course__group=self.course.group)
        return list(qs)

    def _get_collisions_by_teacher(self, qs=None):
        if not qs:
            qs = self._get_same_time_entries_qs()
        qs = qs.filter(teacher=self.teacher)
        return list(qs)

    def _check_collisions(self):
        """
        Check for collisions (if selected teacher or student group
        already have planned lesson at that time)
        """
        raise_error = False
        errors = {}
        qs = self._get_same_time_entries_qs()
        collisions_group = self._get_collisions_by_group(qs)
        collisions_teacher = self._get_collisions_by_teacher(qs)
        error_msg = _("Colliding entries: %(collisions)s")
        if collisions_group:
            errors['course'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_group))
            }
            raise_error = True
        if collisions_teacher:
            errors['teacher'] = error_msg % {
                'collisions': "; ".join(map(str, collisions_teacher))
            }
            raise_error = True

        if raise_error:
            raise ValidationError(errors)

    def clean(self) -> None:
        super().clean()
        # check if ending date isn't earlier than starting date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _("Ending date can't "
                              "be earlier than starting date.")
            })

        # limit schedule length
        dates_diff = self.date_end - self.date_start
        if dates_diff.days > 365:
            raise ValidationError({
                'date_end': _("Schedule length can't exceed 365 days.")
            })

        self.day_of_week = self.date_start.weekday()
        self._check_collisions()

    @property
    def is_editable(self):
        """
        Check for related Lessons with realized or cancelled status.
        Return False if any exist, True otherwise. Used in Schedule
        update view to limit modifiable fields.
        """
        qs = self.lessons.exclude(status=lesson.Lesson.STATUS_PLANNED)
        return False if qs.exists() else True

    def __str__(self) -> str:
        return "{}, {}, {} ({}, {} - {})".format(
            self.course,
            self.course.group,
            self.teacher,
            self.period,
            self.date_start,
            self.date_end
        )

    def get_absolute_url(self):
        kwargs = {
            'pk': self.course.group.pk,
            'date': self.date_start,
            'full_week': 1,
        }
        return reverse_lazy("group:schedule-specified", kwargs=kwargs)

records/models/studentgroup.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth import get_user_model
import datetime

User = get_user_model()


class StudentGroup(models.Model):
    """
    Group of Users without teacher status.
    - StudentGroup_obj.educator - User object set as educator
    """
    class Meta:
        verbose_name = _('Student group')
        verbose_name_plural = _('Student groups')
        ordering = ['name', ]

    name = models.CharField(
        _('Name'),
        blank=False,
        unique=True,
        max_length=30,
    )

    # Educator responsible for the group.
    # Limit choices to Users with is_teacher set to True
    educator = models.OneToOneField(
        verbose_name=_('Educator'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': True},
        related_name='educated_group'
    )

    def get_assignments_by_date(self, date=None):
        """
        Return queryset of assignments to the group for specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        qs = self.assignments.filter(
            date_start__lte=date,
            date_end__gte=date,
        ).select_related('student')
        return qs

    def get_all_assignments(self):
        """
        Return queryset for all assignemts to the group,
        including out of date assignments
        """
        qs = self.assignments.select_related('student')
        return qs

    def get_students_by_date(self, date=None):
        """
        Return queryset of students assigned to the group on specific date,
        if date param not supplied, datetime.date.today() used
        """
        if not date:
            date = datetime.date.today()
        assignments = self.get_assignments_by_date(date)
        current_students = User.objects.filter(
            assignments__in=assignments)
        return current_students

    def get_all_students(self):
        """
        Return queryset of all students assigned to the group,
        including out of date assignments
        """
        all_students = User.objects.filter(
            assignments__in=self.assignments.all()
        ).distinct()
        return all_students

    @property
    def current_assignments(self): return self.get_assignments_by_date()

    @property
    def current_students(self): return self.get_students_by_date()

    def get_absolute_url(self):
        return reverse_lazy('group:detail', kwargs={'pk': self.pk})

    def __str__(self) -> str:
        return str(self.name)


class StudentGroupAssignment(models.Model):
    class Meta:
        verbose_name = _('Group assignment')
        verbose_name_plural = _('Group assignments')
        ordering = ['student__last_name', 'student__first_name', 'date_start']

    student = models.ForeignKey(
        verbose_name=_('Student'),
        to=settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        limit_choices_to={'is_teacher': False},
        related_name='assignments'
    )

    group = models.ForeignKey(
        verbose_name=_('Student group'),
        to=StudentGroup,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
        related_name='assignments'
    )

    date_start = models.DateField(
        _('Start date'),
        blank=False,
        null=False
    )

    date_end = models.DateField(
        _('End date'),
        blank=False,
        null=False
    )

    def _get_colliding_assignments(self):
        qs = StudentGroupAssignment.objects.filter(
            student=self.student,
            date_start__lte=self.date_end,
            date_end__gte=self.date_start
        ).select_related('student', 'group')
        if self.pk:
            qs = qs.exclude(pk=self.pk)
        return qs

    def clean(self):
        super().clean()

        # check if ending date is not earlier than start date
        if self.date_end < self.date_start:
            raise ValidationError({
                'date_end': _(
                    "End date can't be earlier than start date."
                )
            })
        colliding_assignments = list(self._get_colliding_assignments())
        if colliding_assignments:
            raise ValidationError(
                _("Colliding assigments for %(student)s: %(collisions)s"),
                params={
                    'student': str(self.student),
                    'collisions': ", ".join(map(str, colliding_assignments)),
                }
            )

    def __str__(self):
        return "{} ({} - {})".format(
            self.group, self.date_start, self.date_end
        )

templates/includes/mark_modals.html
{% load widget_tweaks %}
{% load static %}

<div id="markModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-flex justify-content-center">
                    <div id="mark-spinner" class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
                <div id="mark-details">

                </div>
            </div>
            <div class="modal-footer">
                {% if perms.recors.view_changehistory %}
                    <button class="btn btn-primary" data-bs-target="#markHistoryModal" data-bs-toggle="modal" data-bs-dismiss="modal">Show history</button>
                {% endif %}
                {% if perms.recors.change_mark %}
                    <button class="btn btn-outline-primary" data-bs-target="#markUpdateModal" data-bs-toggle="modal" data-bs-dismiss="modal">Change</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% if perms.recors.view_changehistory %}
<div id="markHistoryModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Changes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-history">
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#markModal" data-bs-toggle="modal" data-bs-dismiss="modal">Back</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if perms.recors.change_mark %}
<div id="markUpdateModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Update</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-change">
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if perms.recors.add_mark %}
<div id="markCreateModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Add</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-create">
                <form method="post" action="{% url 'ajax:mark-create-lesson' lesson.pk %}">{% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    <div class="form-text">
                        {{ field.help_text }}
                    </div>
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endfor %}
            
                    <div class="container-fluid text-end px-0 mt-3">
                        <button id="create-mark-button" type="submit" name="save" value="save" class="btn btn-success">Save</button>
                        <a class="btn btn-primary" data-bs-dismiss="modal">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}
  
<script src="{% static 'js/marks.js' %}"></script>

templates/includes/mark_modals_create.html
{% load widget_tweaks %}
{% load static %}

{% if perms.recors.add_mark %}
<div id="markCreateModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Add</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-create">
                <form method="post" action="{% url 'ajax:mark-create-lesson' lesson.pk %}">{% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                    <label for="{{ field.id_for_label }}" class="mt-2">{{ field.label }}</label>
                    {{ field|add_class:'form-control' }}
                    <div class="form-text">
                        {{ field.help_text }}
                    </div>
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endfor %}
            
                    <div class="container-fluid text-end px-0 mt-3">
                        <button id="create-mark-button" type="submit" name="save" value="save" class="btn btn-success">Save</button>
                        <a class="btn btn-primary" data-bs-dismiss="modal">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

<script src="{% static 'js/marks_create.js' %}"></script>

templates/includes/mark_modals_details.html
{% load widget_tweaks %}
{% load static %}

<div id="markModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="d-flex justify-content-center">
                    <div id="mark-spinner" class="spinner-border" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </div>
                </div>
                <div id="mark-details">

                </div>
            </div>
            <div class="modal-footer">
                {% if perms.recors.view_changehistory %}
                    <button class="btn btn-primary" data-bs-target="#markHistoryModal" data-bs-toggle="modal" data-bs-dismiss="modal">Show history</button>
                {% endif %}
                {% if perms.recors.change_mark %}
                    <button class="btn btn-outline-primary" data-bs-target="#markUpdateModal" data-bs-toggle="modal" data-bs-dismiss="modal">Change</button>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% if perms.recors.view_changehistory %}
<div id="markHistoryModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Changes</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-history">
            </div>
            <div class="modal-footer">
                <button class="btn btn-primary" data-bs-target="#markModal" data-bs-toggle="modal" data-bs-dismiss="modal">Back</button>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% if perms.recors.change_mark %}
<div id="markUpdateModal" class="modal fade" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Mark - Update</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="mark-change">
            </div>
        </div>
    </div>
</div>
{% endif %}

  
<script src="{% static 'js/marks_details.js' %}"></script>

templates/includes/mark_templates.html
<a id="mark-empty" href="{% url 'ajax:mark-details' %}" class="mark-link btn btn-light btn-sm py-1 my-1 me-1 position-relative visually-hidden">
    <span class="symbol-placeholder"></span>
    <span class="position-absolute top-0 start-100 translate-middle p-1 bg-success border border-light rounded-circle">
        <span class="visually-hidden">New mark</span>
    </span>
</a>
<a id="mark-modified" href="{% url 'ajax:mark-details' %}" class="mark-link btn btn-light btn-sm py-1 my-1 me-1 position-relative visually-hidden">
    <span class="symbol-placeholder"></span>
    <span class="position-absolute top-0 start-100 translate-middle p-1 bg-warning border border-light rounded-circle">
        <span class="visually-hidden">Modified mark</span>
    </span>
</a>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }}" role="alert">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/includes/pagination.html
{% if is_paginated %}
    <div class="d-flex justify-content-center mb-3">
        <div class="btn-group" role="group" style="margin: auto;">
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-primary" href="?page=1"><i class="bi bi-chevron-bar-left"></i></a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.previous_page_number }}"><i class="bi bi-chevron-left"></i></a>
            {% else %}
                <a class="btn btn-outline-secondary disabled"><i class="bi bi-chevron-bar-left"></i></a>
                <a class="btn btn-outline-secondary disabled"><i class="bi bi-chevron-left"></i></a>
            {% endif %}
            {% for i in paginator.page_range %} 
                {% if page_obj.number == i %}
                    <a class="btn btn-primary">{{ i }}</a>
                {% else %}
                    <a class="btn btn-outline-primary" href="?page={{ i }}">{{ i }}</a>
                {% endif %} 
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-primary" href="?page={{ page_obj.next_page_number }}"><i class="bi bi-chevron-right"></i></a>
                <a class="btn btn-outline-primary" href="?page={{ page_obj.paginator.num_pages }}"><i class="bi bi-chevron-bar-right"></i></a>
            {% else %}
                <a class="btn btn-outline-secondary disabled"><i class="bi bi-chevron-right"></i></a>
                <a class="btn btn-outline-secondary disabled"><i class="bi bi-chevron-bar-right"></i></a>
            {% endif %}
        </div>
    </div>
{% endif %}

templates/includes/sidebar.html
<div id="sidebar" class="col-md-4 col-lg-3 bg-dark text-white h-100 px-0 pt-2 pt-md-3">
    <a class="h2 header-brand navbar-brand-small" href="{% url 'dashboard:start' %}">
        <i class="bi bi-book mx-3"></i>eRegister
    </a>
    <button class="navbar-toggler d-md-none collapsed float-end me-3 pt-0" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <i class="bi bi-list" style="color: aliceblue; padding-left: 10px; font-size: 2rem"></i>
    </button>
    <nav id="sidebarMenu" class="navbar navbar-dark collapse d-md-block">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="{% url 'dashboard:start' %}" class="nav-link">
                    <i class="bi bi-house-door"></i>Dashboard
                </a>
            </li>
            {% if perms.records.view_lesson %}
            <li class="nav-item">
                <a href="{% url 'lesson:realized' %}" class="nav-link">
                    <i class="bi bi-easel"></i>Lessons
                </a>
            </li>
            {% endif %}
            {% if perms.records.view_schedule %}
            <li class="nav-item">
                <a href="{% url 'schedule:timetable-my' %}" class="nav-link">
                    <i class="bi bi-table"></i>Schedule
                </a>
            </li>
            {% endif %}
            {% if perms.records.view_student %}
            <li class="nav-item">
                <a href="{% url 'student:list' %}" class="nav-link">
                    <i class="bi bi-person"></i>Students
                </a>
            </li>
            {% endif %}
            {% if perms.records.view_studentgroup %}
            <li class="nav-item">
                <a href="{% url 'group:list' %}" class="nav-link">
                    <i class="bi bi-people"></i>Groups
                </a>
            </li>
            {% endif %}
            <hr />
            {% if request.user.is_staff  %}
            <li class="nav-item">
                <a href="{% url 'admin:index' %}" class="nav-link" target="_blank">
                    <i class="bi bi-tools"></i>Administration
                </a>
            </li>
            <hr />
            {% endif %}
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-toggle="collapse" data-bs-target="#accountMenu"
                    aria-controls="accountMenu" aria-expanded="false">
                    <i class="bi bi-person-circle"></i>{{ request.user }}
                </a>
                <div class="collapse menu-collapse" id="accountMenu">
                    <ul class="list-unstyled">
                        <li><a href="{% url 'auth:logout' %}" class="nav-link">Log out</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
</div>

templates/includes/timetable.html
<table class="table text-center table-bordered mb-0">
    <thead class="border-bottom-0">
        <tr>
            <th style="width:9%">Period</th>
            {% for date, name in days.items %}
                <td style="width:13%">
                    <p class="lead mb-1">{{ name }}</p>
                    <p class="small mb-0">{{ date }}</p>
                </td>
            {% endfor %}
        </tr>
    </thead>
    <tbody class="align-middle">
        {% for period, lessons in timetable.items %}
            <tr>
                <td style="width:9%">
                    <p class="my-0 small text-start">{{ period.time_start }}</p>
                    <p class="mb-2 h4">{{ forloop.counter }}</p>
                    <p class="my-0 small text-end">{{ period.time_end }}</p>
                </td>
                {% for lesson in lessons %}
                    <td style="width:13%" {% if lesson.is_cancelled %}class="table-danger"{% endif %}>
                        {% if lesson %}
                            <div class="px-1">
                                {% if perms.records.change_schedule %}
                                    <a href="{% url 'schedule:edit' lesson.schedule.pk %}?prev={{ request.path }}" class="my-1 fw-bold text-success">{{ lesson.schedule.course }}</a>
                                {% else %}
                                    <p class="my-1 fw-bold text-success">{{ lesson.schedule.course }}</p>
                                {% endif %}
                                {% if lesson.is_cancelled %}
                                    <span class="my-0 badge rounded-pill bg-danger">Cancelled</span>
                                {% endif %}
                                <p class="my-0 small">{{ lesson.schedule.course.group }}</p>
                                <p class="my-0 small">{{ lesson.schedule.teacher }}</p>
                            </div>
                        {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>